slack_token = 'xoxb-19648973122-JySsrhuJwEbI0F5VjzlNF6n1'
slack_username = 'jerkbot'
slack_usercode = 'idk yet'
dbfile = 'jerkbot.db'
reddit_user_agent = 'osx:com.atvaccaro.jerkbot:v0.1 (by /u/theplague42)'
starting_beers = 3
default_markov_length = 40
start_char = '$'
end_char = '%'
