slack_token = 'xoxb-19648973122-JySsrhuJwEbI0F5VjzlNF6n1'
slack_username = 'jerkbot'
slack_usercode = 'idk yet'
dbfile = 'jerkbot.db'
reddit_user_agent = 'osx:com.atvaccaro.jerkbot:v0.1 (by /u/theplague42)'
starting_beers = 3
markov_sentences = 3
markov_sentence_length = 7
word_whitelist = ['LaTeX', 'John', 'Igor', 'Ben', 'Ethan', 'Andrew']
